### ISSUE TITLE
Presence in multiplayer is very delayed.

### ISSUE THREAD

**Issue by nickian563** [PurplefinNeptuna/DiscordRP-tModLoader#5] opened 2019-11-02 15:41 UTC
The presence works perfectly in singleplayer, but in multiplayer it does not. The presence is always either still in the main menu or very delayed. (Sometimes it works.)
![image](https://user-images.githubusercontent.com/30329887/68073358-ba432e80-fd65-11e9-9be8-fcb5602c9452.png)
![image](https://user-images.githubusercontent.com/30329887/68073363-c5965a00-fd65-11e9-9c21-b542314c4983.png)

**Comment by PurplefinNeptuna** [comment] 2020-05-30 08:11
I think it happened because old logic that broken in multiplayer
now I rewrite all the code, and I think it handle multiplayer better
not closing the issues because not tested yet

**Comment by PurplefinNeptuna** [comment] 2020-05-31 11:23
Now fixed in newest version, it actually caused by dumb bugs

**Closed by PurplefinNeptuna** 2020-05-31 11:23 UTC
